name: kMoney
version: 0.1.0
main: me.kwlew.kMoney
api-version: '1.21'
soft-depend: ["PlaceholderAPI", "Vault"]


commands:
  money:
    description: Main money command
    usage: /money <add|remove|set|balance>
    aliases: [eco, balance]
  pay:
    description: Pay another player.
    usage: /pay <player> <amount>

permissions:
  kmoney.admin:
    description: Allows admin money commands
    default: op